version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # su - postgres
  # psql -U user
  postgres:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    # volumes:
    #   - postgres-storage:/var/lib/postgresql/data

# volumes:
#   postgres-storage:
